### ISSUE TITLE
Broken in IE10/11

### ISSUE THREAD

**Issue by jhildenbiddle** [jperasmus/docsify-copy-code#1]
Two issues:

https://github.com/jperasmus/docsify-copy-code/blob/7cbe2d4059492d7e80480cc3b54d2f0f16400325/index.js#L6-L8

1. `querySelectorAll` returns a NodeList, and not all browsers provide a `forEach` method on NodeLists.

1. Arrow functions are not support in IE (or older evergreen browsers). 

Fixed by #3

**Comment by jperasmus** [comment]
Hi @jhildenbiddle, thanks for your contributions, it is much appreciated! I originally put this plugin together quickly for a specific use case we had targeting developers specifically on modern browsers. Thanks for your efforts to improve it.
