### ISSUE TITLE
how about i18n support?

### ISSUE THREAD

**Issue by wizicer** [jperasmus/docsify-copy-code#13]
It would be great to know this plugin supports i18n. Any idea?

**Comment by jperasmus** [comment]
Hi @wizicer, thanks for reaching out. It is not currently something we were planning to add, but we are open to the idea. Would you like to create a PR?

**Comment by wizicer** [comment]
I'm new to docsify, not familiar with its API so far. Maybe after I have migrated my programming book to docsify, I'll create the PR.
BTW, thanks for your great code.

**Comment by jhildenbiddle** [comment]
Fixed in 2.1.0. See updated [README](https://github.com/jperasmus/docsify-copy-code/blob/master/README.md) for details.

**Comment by wizicer** [comment]
@jhildenbiddle thanks, just tried the code, it works like a charm.
BTW: learned a lot from your PR -- complete and intuitive simple, thanks again.

**Comment by jhildenbiddle** [comment]
Happy to help, @wizicer!
