### ISSUE TITLE
The copyed content ends with  a newline

### ISSUE THREAD

**Issue by jintaixizhao** [jperasmus/docsify-copy-code#15]
The copyed content ends with a newline, which is convenient sometimes, would you like to fix it ?

**Comment by jperasmus** [comment]
Hi @jintaixizhao 

Are you saying it should not end with a newline? Would you be willing to contribute a PR?

**Comment by Niek** [comment]
Would it be possible to make the newline optional? When copying bash commands it's a bit annoying, since it will paste an empty newline at the end of the command.
