### ISSUE TITLE
I cannot install the copy code plugin for docsify

### ISSUE THREAD

**Issue by jackmatrix** [jperasmus/docsify-copy-code#18]
I am trying to install the docsify copy code plugin. However it doesn't work nothing change in my HTML yet I did all the required steps to make this works. 

    <script src="//cdn.jsdelivr.net/npm/docsify-copy-code"></script>
    <script>
    window.$docsify = {
    
          copyCode: {
            buttonText : 'Copy to clipboard',
            errorText  : 'Error',
            successText: 'Copied'
          },
          plugins: [
            window.DocsifyCopyCodePlugin.init()
          ]
        }
    <srcipt>
   

In my console log I have this error 

  ```
(DevTools failed to load SourceMap: Could not load content for https://unpkg.com/docsify-copy-code.min.js.map: 
   HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)
```

Any suggestion ?

**Comment by jperasmus** [comment]
Hi @jackmatrix You can try adding the first script tag below the `window.$docsify` config object's script. If that doesn't work, here is an example of the plugin used in the wild that might give you some more insights: https://github.com/flamelink/flamelink-js-sdk/blob/master/docs/index.html

**Comment by jackmatrix** [comment]
Thank you. Works fine now . I put the script tag below `window.$docsify` as you advised and I switched `<script src="//cdn.jsdelivr.net/npm/docsify-copy-code"></script>` to `<script src="//unpkg.com/docsify-copy-code"></script>`. So Finally it works.

Thanks again.

**Comment by jperasmus** [comment]
Awesome! I'm glad to hear it is working now.
