### ISSUE TITLE
Upon invoking "Copy to Clipboard" button, the Screen reader is not announcing the success message "Copied". 

### ISSUE THREAD

**Issue by msftedad** [jperasmus/docsify-copy-code#63]
**Steps to reproduce**
1.Navigate to this link [First Level Child (zorana-jankovic.github.io)](https://zorana-jankovic.github.io/example/#/start)
2.Turn on screen reader.
3.Tab navigate to the "Copy to Clipboard" button and invoke it.
4.Observe that screenreader is announcing the success message copied/not.

**What is current behaviour**
Upon invoking "Copy to Clipboard" button, the Narrator is not announcing the success message "Copied".

**What is the expected behaviour**
Upon invoking "Copy to Clipboard" button, the Narrator should announce the success message "Copied".
Note: Issue occurs in NVDA, JAWS also

**Other relevant information**
Your OS: OS build (22621.1265)
Browser version: Version 110.0.1587.50 (Official build) (64-bit)
NVDA version: 2022.3.2
JAWS version: 2023.2212.23 ILM

Microsoft tracking Id: ACCESSIBILITY 204134

https://user-images.githubusercontent.com/93735775/222434285-8302d013-c543-4853-9344-89a37e5e7809.mp4

**Comment by sombek** [comment]
That's interesting bug.
I think if there is a way to move the focus to the tooltip the reader would pick it up

**Comment by jperasmus** [comment]
Thanks for reporting this issue. I am not currently using this so my maintenance efforts on the library are minimal. We can likely get this better announced by using the Aria live regions. I'll take a look.

**Comment by jperasmus** [comment]
Screen readers should now announce the text copy correctly from v3.0.0

**Comment by msftedad** [comment]
Hi @jperasmus, could you please provide version details as we are unable to get as its only mentioned v3.0.0.

**Comment by jperasmus** [comment]
Hi @msftedad What type of details are you looking for? The screen reader announcement feature is available from the `v3.0.0` version so you would need to upgrade to that version. The reason why it was a major version change was to be safe from my side since I upgraded the full build process and dropped Node.js versions below v14.

**Comment by msftedad** [comment]
Hi @jperasmus, Can you please provide test environment details as issue is still reproducible from our end. Thanks

**Comment by jperasmus** [comment]
Can you upgrade to use the latest version of the plugin? If I look at the example you linked in the issue description, I can see you are loading a local version of `docsify-copy-code.min.js` which is still for an older version.
![Screenshot 2023-11-28 at 13 36 07](https://github.com/jperasmus/docsify-copy-code/assets/6787452/ac90a866-f62d-474d-80ca-dd64adc4ba59)
