### ISSUE TITLE
Release v3.0.0?

### ISSUE THREAD

**Issue by muzso** [jperasmus/docsify-copy-code#70]
Hi!

Do you plan to release v3.0.0 officially (as in tag it)?
The current latest (tagged) release is 2.1.1, but there have been quite a few commits since 2020-09-21 (26, not counting dependabot commits).
It'd be nice if you consider it stable enough. The various CDN distribution services (e.g. jsdelivr.net, etc.) could pick up on it and a lot more people would start to test and use it.

**Comment by jperasmus** [comment]
Hi!

I'm probably missing something, but it is tagged as `v3.0.0` and available on NPM and `jsdelivr.com`, etc. because of it. What am I missing here?

https://www.jsdelivr.com/package/npm/docsify-copy-code points to v3.0.0

**Comment by muzso** [comment]
> Hi!
> 
> I'm probably missing something, but it is tagged as `v3.0.0` and available on NPM and `jsdelivr.com`, etc. because of it. What am I missing here?
> 
> https://www.jsdelivr.com/package/npm/docsify-copy-code points to v3.0.0

Honestly I'm not sure.
I see now that npmjs has 3.0.0 as the latest version.
https://www.npmjs.com/package/docsify-copy-code?activeTab=versions

And jsdelivr.net has 3.0.0 too.
https://cdn.jsdelivr.net/npm/docsify-copy-code/

I don't what I saw on Friday that made me ask this question.
The only thing that I can think of is that there's no 3.0.0 tag on the Git repo:
https://github.com/jperasmus/docsify-copy-code/tags

But I've to apologize since both npmjs and jsdelivr have the 3.0.0 version.
So I'm very sorry for bugging you about this unnecessarily.
Mea culpa.

**Comment by jperasmus** [comment]
I'll have to check out the git tag to see why it isn't showing up. When I first saw your post it sounded very possible that I could've forgotten to publish it. I am not actively maintaining this package since it's not something I am using myself. But, I do try and assist when something pops up every now and then.

I'll go ahead and close this issue then.

**Comment by jhildenbiddle** [comment]
@jperasmus --

> I'll have to check out the git tag to see why it isn't showing up.

Looks like the repo I just missing the 3.0.0 [tag](https://github.com/jperasmus/docsify-copy-code/tags).

**Comment by jperasmus** [comment]
🙈 Thanks @jhildenbiddle I've pushed the tag now. I can't remember that I ever explicitly had to push the tags before.
